"""add workouts.started_at

Revision ID: 1621297e5096
Revises: 230254981819
Create Date: 2026-06-04 12:29:46.806794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1621297e5096'
down_revision: Union[str, None] = '230254981819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'started_at')
    # ### end Alembic commands ###
