"""add daily_briefings table

Revision ID: 230254981819
Revises: 86f5ce2ce176
Create Date: 2026-06-04 12:17:20.466473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '230254981819'
down_revision: Union[str, None] = '86f5ce2ce176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_briefing_user_date')
    )
    op.create_index(op.f('ix_daily_briefings_id'), 'daily_briefings', ['id'], unique=False)
    op.create_index(op.f('ix_daily_briefings_user_id'), 'daily_briefings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_briefings_user_id'), table_name='daily_briefings')
    op.drop_index(op.f('ix_daily_briefings_id'), table_name='daily_briefings')
    op.drop_table('daily_briefings')
    # ### end Alembic commands ###
