"""add whoop_id and source to workouts

Revision ID: 86f5ce2ce176
Revises: ac8429bf07c6
Create Date: 2026-06-03 22:24:37.549480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '86f5ce2ce176'
down_revision: Union[str, None] = 'ac8429bf07c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('whoop_id', sa.String(length=100), nullable=True))
    op.add_column('workouts', sa.Column('source', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False))
    op.create_unique_constraint('uq_workouts_whoop_id', 'workouts', ['whoop_id'])
    # Existing rows defaulted to 'manual'; mark the Strava-synced ones correctly.
    op.execute("UPDATE workouts SET source = 'strava' WHERE strava_id IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workouts_whoop_id', 'workouts', type_='unique')
    op.drop_column('workouts', 'source')
    op.drop_column('workouts', 'whoop_id')
    # ### end Alembic commands ###
