"""add unique constraint on recovery user_id date

Revision ID: ac8429bf07c6
Revises: 84dc31ec57af
Create Date: 2026-06-03 16:14:11.373678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac8429bf07c6'
down_revision: Union[str, None] = '84dc31ec57af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_recovery_user_date', 'recovery_scores', ['user_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_recovery_user_date', 'recovery_scores', type_='unique')
    # ### end Alembic commands ###
