"""add glucose_readings table and dexcom token columns

Revision ID: b3f1c9a2d7e4
Revises: 1621297e5096
Create Date: 2026-06-04 14:40:00.000000

Hand-written (not autogenerated): the change is purely additive — two nullable
columns on `users` plus a new `glucose_readings` table — so the diff is known and
this needs no live DB to author. Mirrors models/glucose.py and models/user.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b3f1c9a2d7e4'
down_revision: Union[str, None] = '1621297e5096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Encrypted Dexcom OAuth tokens, alongside the existing whoop_/strava_ pairs.
    op.add_column('users', sa.Column('dexcom_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('dexcom_refresh_token', sa.Text(), nullable=True))

    op.create_table(
        'glucose_readings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('system_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('value_mgdl', sa.Integer(), nullable=False),
        sa.Column('trend', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'system_time', name='uq_glucose_user_time'),
    )
    op.create_index(op.f('ix_glucose_readings_id'), 'glucose_readings', ['id'], unique=False)
    op.create_index(op.f('ix_glucose_readings_user_id'), 'glucose_readings', ['user_id'], unique=False)
    # Composite index backing the windowed time-range queries the analysis runs.
    op.create_index('ix_glucose_user_time', 'glucose_readings', ['user_id', 'system_time'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_glucose_user_time', table_name='glucose_readings')
    op.drop_index(op.f('ix_glucose_readings_user_id'), table_name='glucose_readings')
    op.drop_index(op.f('ix_glucose_readings_id'), table_name='glucose_readings')
    op.drop_table('glucose_readings')
    op.drop_column('users', 'dexcom_refresh_token')
    op.drop_column('users', 'dexcom_access_token')
